mpk_cms_homepage:
    path:     /
    defaults: { _controller: MpkCmsBundle:Default:index }

mpk_cms_single_page:
    path:     /single-page/{id}
    defaults: { _controller: MpkCmsBundle:Default:singlePage }

mpk_cms_services:
    path:     /services
    defaults: { _controller: MpkCmsBundle:Default:services }

mpk_cms_contact:
    path:     /contact
    defaults: { _controller: MpkCmsBundle:Default:contact }
